############################################################################
# apps/examples/w25bench/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_W25BENCH_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_W25BENCH_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_W25BENCH_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_W25BENCH)

MAINSRC = w25bench_main.c

include $(APPDIR)/Application.mk
